/*
 * generated by Xtext 2.13.0
 */
package net.unicoen.ui.tests;

import com.google.inject.Injector;
import net.unicoen.ui.internal.UnicoenActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class UniMapperGeneratorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UnicoenActivator.getInstance().getInjector("net.unicoen.UniMapperGenerator");
	}

}
