/*
 * generated by Xtext 2.13.0
 */
package net.unicoen.ui;

import com.google.inject.Injector;
import net.unicoen.ui.internal.UnicoenActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UniMapperGeneratorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(UnicoenActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		UnicoenActivator activator = UnicoenActivator.getInstance();
		return activator != null ? activator.getInjector(UnicoenActivator.NET_UNICOEN_UNIMAPPERGENERATOR) : null;
	}

}
