/**
 * generated by Xtext 2.13.0
 */
package net.unicoen.validation;

import net.unicoen.validation.AbstractUniMapperGeneratorValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class UniMapperGeneratorValidator extends AbstractUniMapperGeneratorValidator {
}
