/**
 * generated by Xtext 2.13.0
 */
package net.unicoen;

import net.unicoen.AbstractUniMapperGeneratorRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class UniMapperGeneratorRuntimeModule extends AbstractUniMapperGeneratorRuntimeModule {
}
