/**
 * generated by Xtext 2.13.0
 */
package net.unicoen.ui;

import net.unicoen.ui.AbstractUniMapperGeneratorUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class UniMapperGeneratorUiModule extends AbstractUniMapperGeneratorUiModule {
  public UniMapperGeneratorUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
