/**
 * generated by Xtext 2.13.0
 */
package net.unicoen.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import net.unicoen.UniMapperGeneratorRuntimeModule;
import net.unicoen.UniMapperGeneratorStandaloneSetup;
import net.unicoen.ide.UniMapperGeneratorIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class UniMapperGeneratorIdeSetup extends UniMapperGeneratorStandaloneSetup {
  @Override
  public Injector createInjector() {
    UniMapperGeneratorRuntimeModule _uniMapperGeneratorRuntimeModule = new UniMapperGeneratorRuntimeModule();
    UniMapperGeneratorIdeModule _uniMapperGeneratorIdeModule = new UniMapperGeneratorIdeModule();
    return Guice.createInjector(Modules2.mixin(_uniMapperGeneratorRuntimeModule, _uniMapperGeneratorIdeModule));
  }
}
