/**
 * generated by Xtext 2.13.0
 */
package net.unicoen.uniMapperGenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.unicoen.uniMapperGenerator.ActionElement#getBody <em>Body</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.ActionElement#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getActionElement()
 * @model
 * @generated
 */
public interface ActionElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' attribute.
   * @see #setBody(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getActionElement_Body()
   * @model
   * @generated
   */
  String getBody();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ActionElement#getBody <em>Body</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' attribute.
   * @see #getBody()
   * @generated
   */
  void setBody(String value);

  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Options</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference.
   * @see #setOptions(ElementOptions)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getActionElement_Options()
   * @model containment="true"
   * @generated
   */
  ElementOptions getOptions();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ActionElement#getOptions <em>Options</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Options</em>' containment reference.
   * @see #getOptions()
   * @generated
   */
  void setOptions(ElementOptions value);

} // ActionElement
