/**
 * generated by Xtext 2.15.0
 */
package net.unicoen.uniMapperGenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ebnf Suffix</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.unicoen.uniMapperGenerator.EbnfSuffix#getOperator <em>Operator</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.EbnfSuffix#getNongreedy <em>Nongreedy</em>}</li>
 * </ul>
 *
 * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getEbnfSuffix()
 * @model
 * @generated
 */
public interface EbnfSuffix extends EObject
{
  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see #setOperator(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getEbnfSuffix_Operator()
   * @model
   * @generated
   */
  String getOperator();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.EbnfSuffix#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see #getOperator()
   * @generated
   */
  void setOperator(String value);

  /**
   * Returns the value of the '<em><b>Nongreedy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nongreedy</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nongreedy</em>' attribute.
   * @see #setNongreedy(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getEbnfSuffix_Nongreedy()
   * @model
   * @generated
   */
  String getNongreedy();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.EbnfSuffix#getNongreedy <em>Nongreedy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nongreedy</em>' attribute.
   * @see #getNongreedy()
   * @generated
   */
  void setNongreedy(String value);

} // EbnfSuffix
