/**
 * generated by Xtext 2.13.0
 */
package net.unicoen.uniMapperGenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exception Handler</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.unicoen.uniMapperGenerator.ExceptionHandler#getException <em>Exception</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.ExceptionHandler#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getExceptionHandler()
 * @model
 * @generated
 */
public interface ExceptionHandler extends EObject
{
  /**
   * Returns the value of the '<em><b>Exception</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exception</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exception</em>' attribute.
   * @see #setException(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getExceptionHandler_Exception()
   * @model
   * @generated
   */
  String getException();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ExceptionHandler#getException <em>Exception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exception</em>' attribute.
   * @see #getException()
   * @generated
   */
  void setException(String value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' attribute.
   * @see #setBody(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getExceptionHandler_Body()
   * @model
   * @generated
   */
  String getBody();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ExceptionHandler#getBody <em>Body</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' attribute.
   * @see #getBody()
   * @generated
   */
  void setBody(String value);

} // ExceptionHandler
