/**
 * generated by Xtext 2.15.0
 */
package net.unicoen.uniMapperGenerator;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grammar Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.unicoen.uniMapperGenerator.GrammarAction#getScope <em>Scope</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.GrammarAction#getColonSymbol <em>Colon Symbol</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.GrammarAction#getName <em>Name</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.GrammarAction#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getGrammarAction()
 * @model
 * @generated
 */
public interface GrammarAction extends PrequelConstruct
{
  /**
   * Returns the value of the '<em><b>Scope</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scope</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' attribute.
   * @see #setScope(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getGrammarAction_Scope()
   * @model
   * @generated
   */
  String getScope();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.GrammarAction#getScope <em>Scope</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' attribute.
   * @see #getScope()
   * @generated
   */
  void setScope(String value);

  /**
   * Returns the value of the '<em><b>Colon Symbol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Colon Symbol</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colon Symbol</em>' attribute.
   * @see #setColonSymbol(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getGrammarAction_ColonSymbol()
   * @model
   * @generated
   */
  String getColonSymbol();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.GrammarAction#getColonSymbol <em>Colon Symbol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Colon Symbol</em>' attribute.
   * @see #getColonSymbol()
   * @generated
   */
  void setColonSymbol(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getGrammarAction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.GrammarAction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getGrammarAction_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.GrammarAction#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

} // GrammarAction
