/**
 * generated by Xtext 2.13.0
 */
package net.unicoen.uniMapperGenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lexer Command Arg</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getLexerCommandArg()
 * @model
 * @generated
 */
public interface LexerCommandArg extends EObject
{
} // LexerCommandArg
