/**
 * generated by Xtext 2.15.0
 */
package net.unicoen.uniMapperGenerator;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parser Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.unicoen.uniMapperGenerator.ParserRule#getArgs <em>Args</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.ParserRule#getReturn <em>Return</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.ParserRule#getThrows <em>Throws</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.ParserRule#getLocals <em>Locals</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.ParserRule#getPrequels <em>Prequels</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.ParserRule#getBody <em>Body</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.ParserRule#getCaught <em>Caught</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.ParserRule#getSemicolonSymbol <em>Semicolon Symbol</em>}</li>
 * </ul>
 *
 * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getParserRule()
 * @model
 * @generated
 */
public interface ParserRule extends Rule
{
  /**
   * Returns the value of the '<em><b>Args</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' attribute.
   * @see #setArgs(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getParserRule_Args()
   * @model
   * @generated
   */
  String getArgs();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ParserRule#getArgs <em>Args</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' attribute.
   * @see #getArgs()
   * @generated
   */
  void setArgs(String value);

  /**
   * Returns the value of the '<em><b>Return</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Return</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return</em>' containment reference.
   * @see #setReturn(Return)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getParserRule_Return()
   * @model containment="true"
   * @generated
   */
  Return getReturn();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ParserRule#getReturn <em>Return</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return</em>' containment reference.
   * @see #getReturn()
   * @generated
   */
  void setReturn(Return value);

  /**
   * Returns the value of the '<em><b>Throws</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Throws</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Throws</em>' containment reference.
   * @see #setThrows(Exceptions)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getParserRule_Throws()
   * @model containment="true"
   * @generated
   */
  Exceptions getThrows();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ParserRule#getThrows <em>Throws</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Throws</em>' containment reference.
   * @see #getThrows()
   * @generated
   */
  void setThrows(Exceptions value);

  /**
   * Returns the value of the '<em><b>Locals</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Locals</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Locals</em>' containment reference.
   * @see #setLocals(LocalVars)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getParserRule_Locals()
   * @model containment="true"
   * @generated
   */
  LocalVars getLocals();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ParserRule#getLocals <em>Locals</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Locals</em>' containment reference.
   * @see #getLocals()
   * @generated
   */
  void setLocals(LocalVars value);

  /**
   * Returns the value of the '<em><b>Prequels</b></em>' containment reference list.
   * The list contents are of type {@link net.unicoen.uniMapperGenerator.RulePrequel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prequels</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prequels</em>' containment reference list.
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getParserRule_Prequels()
   * @model containment="true"
   * @generated
   */
  EList<RulePrequel> getPrequels();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(RuleAltList)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getParserRule_Body()
   * @model containment="true"
   * @generated
   */
  RuleAltList getBody();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ParserRule#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(RuleAltList value);

  /**
   * Returns the value of the '<em><b>Caught</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Caught</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Caught</em>' containment reference.
   * @see #setCaught(ExceptionGroup)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getParserRule_Caught()
   * @model containment="true"
   * @generated
   */
  ExceptionGroup getCaught();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ParserRule#getCaught <em>Caught</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Caught</em>' containment reference.
   * @see #getCaught()
   * @generated
   */
  void setCaught(ExceptionGroup value);

  /**
   * Returns the value of the '<em><b>Semicolon Symbol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Semicolon Symbol</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semicolon Symbol</em>' attribute.
   * @see #setSemicolonSymbol(String)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getParserRule_SemicolonSymbol()
   * @model
   * @generated
   */
  String getSemicolonSymbol();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.ParserRule#getSemicolonSymbol <em>Semicolon Symbol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semicolon Symbol</em>' attribute.
   * @see #getSemicolonSymbol()
   * @generated
   */
  void setSemicolonSymbol(String value);

} // ParserRule
