/**
 * generated by Xtext 2.13.0
 */
package net.unicoen.uniMapperGenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.unicoen.uniMapperGenerator.RuleRef#getReference <em>Reference</em>}</li>
 *   <li>{@link net.unicoen.uniMapperGenerator.RuleRef#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getRuleRef()
 * @model
 * @generated
 */
public interface RuleRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reference</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' reference.
   * @see #setReference(ParserRule)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getRuleRef_Reference()
   * @model
   * @generated
   */
  ParserRule getReference();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.RuleRef#getReference <em>Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' reference.
   * @see #getReference()
   * @generated
   */
  void setReference(ParserRule value);

  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Options</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference.
   * @see #setOptions(ElementOptions)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getRuleRef_Options()
   * @model containment="true"
   * @generated
   */
  ElementOptions getOptions();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.RuleRef#getOptions <em>Options</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Options</em>' containment reference.
   * @see #getOptions()
   * @generated
   */
  void setOptions(ElementOptions value);

} // RuleRef
