/**
 * generated by Xtext 2.15.0
 */
package net.unicoen.uniMapperGenerator;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Token Vocab</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.unicoen.uniMapperGenerator.TokenVocab#getImportURI <em>Import URI</em>}</li>
 * </ul>
 *
 * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getTokenVocab()
 * @model
 * @generated
 */
public interface TokenVocab extends Option
{
  /**
   * Returns the value of the '<em><b>Import URI</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Import URI</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import URI</em>' reference.
   * @see #setImportURI(Grammar)
   * @see net.unicoen.uniMapperGenerator.UniMapperGeneratorPackage#getTokenVocab_ImportURI()
   * @model
   * @generated
   */
  Grammar getImportURI();

  /**
   * Sets the value of the '{@link net.unicoen.uniMapperGenerator.TokenVocab#getImportURI <em>Import URI</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Import URI</em>' reference.
   * @see #getImportURI()
   * @generated
   */
  void setImportURI(Grammar value);

} // TokenVocab
